// frontend/lib/compiler.js

export const compileToTerraform = (nodes, edges) => {
  let tfCode = `# --------------------------------------------------------\n`;
  tfCode += `# GENERATED BY INGEN COMPILER \n`;
  tfCode += `# Target: AWS Terraform (HCL) \n`;
  tfCode += `# --------------------------------------------------------\n\n`;

  tfCode += `provider "aws" {\n`;
  tfCode += `  region = "us-east-1"\n`;
  tfCode += `}\n\n`;

  // Helper to make safe Terraform names
  const getSafeName = (label) => label.toLowerCase().replace(/[^a-z0-9]/g, '_');

  // 1. GENERATE RESOURCES
  tfCode += `# --- RESOURCES ---\n\n`;
  nodes.forEach((node) => {
    const safeName = getSafeName(node.data.label);

    switch (node.data.service) {
      case 'lambda':
        tfCode += `resource "aws_lambda_function" "${safeName}" {\n`;
        tfCode += `  function_name = "${node.data.label}"\n`;
        tfCode += `  runtime       = "nodejs18.x"\n`;
        tfCode += `  handler       = "index.handler"\n`;
        tfCode += `  filename      = "placeholder.zip"\n`;
        tfCode += `  role          = aws_iam_role.${safeName}_role.arn\n`;
        tfCode += `}\n\n`;
        break;
      case 'apiGateway':
        tfCode += `resource "aws_api_gateway_rest_api" "${safeName}" {\n`;
        tfCode += `  name = "${node.data.label}"\n`;
        tfCode += `}\n\n`;
        break;
      case 's3':
        tfCode += `resource "aws_s3_bucket" "${safeName}" {\n`;
        tfCode += `  bucket = "${node.data.label.toLowerCase().replace(/\s+/g, '-')}"\n`;
        tfCode += `}\n\n`;
        break;
      case 'dynamodb':
        tfCode += `resource "aws_dynamodb_table" "${safeName}" {\n`;
        tfCode += `  name         = "${node.data.label}"\n`;
        tfCode += `  billing_mode = "PAY_PER_REQUEST"\n`;
        tfCode += `  hash_key     = "id"\n`;
        tfCode += `  attribute {\n`;
        tfCode += `    name = "id"\n`;
        tfCode += `    type = "S"\n`;
        tfCode += `  }\n`;
        tfCode += `}\n\n`;
        break;
      case 'sqs':
        tfCode += `resource "aws_sqs_queue" "${safeName}" {\n`;
        tfCode += `  name = "${node.data.label}"\n`;
        tfCode += `}\n\n`;
        break;
      case 'sns':
        tfCode += `resource "aws_sns_topic" "${safeName}" {\n`;
        tfCode += `  name = "${node.data.label}"\n`;
        tfCode += `}\n\n`;
        break;
      case 'eventbridge':
        tfCode += `resource "aws_cloudwatch_event_bus" "${safeName}" {\n`;
        tfCode += `  name = "${node.data.label}"\n`;
        tfCode += `}\n\n`;
        break;
      case 'cognito':
        tfCode += `resource "aws_cognito_user_pool" "${safeName}" {\n`;
        tfCode += `  name = "${node.data.label}"\n`;
        tfCode += `}\n\n`;
        break;
    }
  });

  // 2. GENERATE IAM ROLES & POLICIES (The Magic)
  tfCode += `# --- IAM ROLES & POLICIES ---\n\n`;
  
  nodes.forEach((node) => {
    if (node.data.service === 'lambda') {
      const safeName = getSafeName(node.data.label);
      
      // Basic execution role for the Lambda
      tfCode += `resource "aws_iam_role" "${safeName}_role" {\n`;
      tfCode += `  name = "${safeName}_execution_role"\n`;
      tfCode += `  assume_role_policy = jsonencode({\n`;
      tfCode += `    Version = "2012-10-17"\n`;
      tfCode += `    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "lambda.amazonaws.com" } }]\n`;
      tfCode += `  })\n`;
      tfCode += `}\n\n`;

      const outgoingEdges = edges.filter(e => e.source === node.id);
      const statements = [];

      outgoingEdges.forEach((edge) => {
        const targetNode = nodes.find(n => n.id === edge.target);
        if (!targetNode) return;

        const targetSafeName = getSafeName(targetNode.data.label);

        if (targetNode.data.service === 's3') {
          statements.push(
            `      {\n        Action   = ["s3:GetObject", "s3:PutObject"]\n        Effect   = "Allow"\n        Resource = "\${aws_s3_bucket.${targetSafeName}.arn}/*"\n      }`
          );
        } else if (targetNode.data.service === 'dynamodb') {
          statements.push(
            `      {\n        Action   = ["dynamodb:PutItem", "dynamodb:GetItem", "dynamodb:Scan"]\n        Effect   = "Allow"\n        Resource = aws_dynamodb_table.${targetSafeName}.arn\n      }`
          );
        } else if (targetNode.data.service === 'sqs') {
          statements.push(
            `      {\n        Action   = ["sqs:SendMessage"]\n        Effect   = "Allow"\n        Resource = aws_sqs_queue.${targetSafeName}.arn\n      }`
          );
        }
      });

      if (statements.length > 0) {
        tfCode += `resource "aws_iam_role_policy" "${safeName}_policy" {\n`;
        tfCode += `  name = "${safeName}_policy"\n`;
        tfCode += `  role = aws_iam_role.${safeName}_role.id\n`;
        tfCode += `  policy = jsonencode({\n`;
        tfCode += `    Version = "2012-10-17"\n`;
        tfCode += `    Statement = [\n`;
        tfCode += statements.join(',\n');
        tfCode += `\n    ]\n`;
        tfCode += `  })\n`;
        tfCode += `}\n\n`;
      }
    }
  });

  // 3. GENERATE LAMBDA PERMISSIONS (API Gateway → Lambda)
  const apigwToLambdaEdges = edges.filter((edge) => {
    const source = nodes.find(n => n.id === edge.source);
    const target = nodes.find(n => n.id === edge.target);
    return source?.data.service === 'apiGateway' && target?.data.service === 'lambda';
  });

  if (apigwToLambdaEdges.length > 0) {
    tfCode += `# --- LAMBDA PERMISSIONS ---\n\n`;
    apigwToLambdaEdges.forEach((edge) => {
      const apigwNode = nodes.find(n => n.id === edge.source);
      const lambdaNode = nodes.find(n => n.id === edge.target);
      const apigwSafeName = getSafeName(apigwNode.data.label);
      const lambdaSafeName = getSafeName(lambdaNode.data.label);

      tfCode += `resource "aws_lambda_permission" "${lambdaSafeName}_apigw" {\n`;
      tfCode += `  statement_id  = "AllowAPIGatewayInvoke"\n`;
      tfCode += `  action        = "lambda:InvokeFunction"\n`;
      tfCode += `  function_name = aws_lambda_function.${lambdaSafeName}.function_name\n`;
      tfCode += `  principal     = "apigateway.amazonaws.com"\n`;
      tfCode += `  source_arn    = "\${aws_api_gateway_rest_api.${apigwSafeName}.execution_arn}/*/*"\n`;
      tfCode += `}\n\n`;
    });
  }

  return tfCode;
};