export const SERVICE_DEFAULTS = {
  lambda: {
    timeout: 30,
    memorySize: 128,
    hasDeadLetterQueue: false,
    runtime: 'nodejs20.x',
    architecture: 'x86_64',
    reservedConcurrency: -1,
    vpcEnabled: false,
    environmentVariables: [],
  },
  sqs: {
    visibilityTimeout: 30,
    isFifo: false,
    messageRetentionSeconds: 345600,
    deliveryDelaySeconds: 0,
    maxMessageSize: 262144,
    sqsEncryption: false,
    dlqEnabled: false,
    maxReceiveCount: 3,
  },
  s3: {
    blockPublicAccess: true,
    versioning: false,
    encryption: true,
    staticWebsiteHosting: false,
    lifecycleEnabled: false,
    replicationEnabled: false,
    encryptionType: 'SSE-S3',
    objectLock: false,
    accessLogging: false,
  },
  apiGateway: {
    throttlingEnabled: true,
    loggingEnabled: false,
    apiType: 'REST',
    stageName: 'prod',
    rateLimit: 0,
    burstLimit: 0,
    cacheEnabled: false,
    cacheTtl: 300,
    wafEnabled: false,
    corsEnabled: false,
    corsOrigin: '*',
  },
  dynamodb: {
    pointInTimeRecovery: true,
    billingMode: 'PAY_PER_REQUEST',
    readCapacity: 5,
    writeCapacity: 5,
    ttlEnabled: false,
    encryption: true,
    streamsEnabled: false,
    streamViewType: 'NEW_AND_OLD_IMAGES',
    globalTable: false,
  },
  sns: {
    topicType: 'Standard',
    deliveryRetryEnabled: true,
    snsEncryption: false,
    accessPolicy: 'Restricted',
    filterPolicyEnabled: false,
  },
  eventbridge: {
    isCustomBus: false,
    archiveEnabled: false,
    archiveRetentionDays: 7,
    schemaDiscovery: false,
  },
  cognito: {
    mfaMode: 'OFF',
    accountRecovery: 'PHONE_WITHOUT_MFA',
    accessTokenValidityHours: 1,
    refreshTokenValidityDays: 30,
    advancedSecurity: false,
    passwordMinLength: 8,
    passwordRequireUppercase: true,
    passwordRequireLowercase: true,
    passwordRequireNumbers: true,
    passwordRequireSymbols: false,
  },
};

export function getServiceDefaults(serviceType) {
  return SERVICE_DEFAULTS[serviceType] || {};
}
