export const TEMPLATES = [
  {
    id: 'standard-web-api',
    name: 'Standard Web API',
    description: 'The classic serverless backend. API Gateway routes HTTP requests to Lambda, which reads and writes to DynamoDB.',
    nodes: [
      {
        id: 'apigw',
        type: 'awsNode',
        position: { x: 100, y: 280 },
        data: { service: 'apiGateway', label: 'API Gateway', throttlingEnabled: false, loggingEnabled: false },
      },
      {
        id: 'lambda',
        type: 'awsNode',
        position: { x: 380, y: 280 },
        data: { service: 'lambda', label: 'Lambda Function', timeout: 30, memorySize: 128, hasDeadLetterQueue: false },
      },
      {
        id: 'dynamodb',
        type: 'awsNode',
        position: { x: 660, y: 280 },
        data: { service: 'dynamodb', label: 'DynamoDB', pointInTimeRecovery: true, billingMode: 'PAY_PER_REQUEST' },
      },
    ],
    edges: [
      {
        id: 'e-apigw-lambda',
        source: 'apigw',
        target: 'lambda',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'COGNITO', invocationType: 'Sync', iamPermissions: [] },
      },
      {
        id: 'e-lambda-dynamodb',
        source: 'lambda',
        target: 'dynamodb',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Sync', iamPermissions: [] },
      },
    ],
  },
  {
    id: 'event-driven-pipeline',
    name: 'Event-Driven Pipeline',
    description: 'Decoupled async processing. EventBridge fans out events to SQS, which buffers them for a Lambda worker. Failures go to SNS for alerting.',
    nodes: [
      {
        id: 'eventbridge',
        type: 'awsNode',
        position: { x: 80, y: 280 },
        data: { service: 'eventbridge', label: 'EventBridge' },
      },
      {
        id: 'sqs',
        type: 'awsNode',
        position: { x: 360, y: 280 },
        data: { service: 'sqs', label: 'SQS Queue', visibilityTimeout: 180, isFifo: false },
      },
      {
        id: 'lambda',
        type: 'awsNode',
        position: { x: 640, y: 280 },
        data: { service: 'lambda', label: 'Lambda Worker', timeout: 30, memorySize: 128, hasDeadLetterQueue: true },
      },
      {
        id: 'sns',
        type: 'awsNode',
        position: { x: 920, y: 280 },
        data: { service: 'sns', label: 'SNS Alert' },
      },
    ],
    edges: [
      {
        id: 'e-eb-sqs',
        source: 'eventbridge',
        target: 'sqs',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Async', iamPermissions: [] },
      },
      {
        id: 'e-sqs-lambda',
        source: 'sqs',
        target: 'lambda',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Async', iamPermissions: [] },
      },
      {
        id: 'e-lambda-sns',
        source: 'lambda',
        target: 'sns',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Async', iamPermissions: [] },
      },
    ],
  },
  {
    id: 'static-site-auth-api',
    name: 'Static Site + Authenticated API',
    description: 'Frontend served from S3, authenticated API via Cognito, Lambda handles business logic with DynamoDB persistence.',
    nodes: [
      {
        id: 's3',
        type: 'awsNode',
        position: { x: 80, y: 160 },
        data: { service: 's3', label: 'S3 Frontend', blockPublicAccess: true, versioning: true, encryption: false },
      },
      {
        id: 'cognito',
        type: 'awsNode',
        position: { x: 360, y: 160 },
        data: { service: 'cognito', label: 'Cognito User Pool' },
      },
      {
        id: 'apigw',
        type: 'awsNode',
        position: { x: 80, y: 380 },
        data: { service: 'apiGateway', label: 'API Gateway', throttlingEnabled: false, loggingEnabled: false },
      },
      {
        id: 'lambda',
        type: 'awsNode',
        position: { x: 360, y: 380 },
        data: { service: 'lambda', label: 'Lambda Handler', timeout: 15, memorySize: 128, hasDeadLetterQueue: false },
      },
      {
        id: 'dynamodb',
        type: 'awsNode',
        position: { x: 640, y: 380 },
        data: { service: 'dynamodb', label: 'DynamoDB', pointInTimeRecovery: true, billingMode: 'PAY_PER_REQUEST' },
      },
    ],
    edges: [
      {
        id: 'e-apigw-lambda',
        source: 'apigw',
        target: 'lambda',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'COGNITO', invocationType: 'Sync', iamPermissions: [] },
      },
      {
        id: 'e-lambda-dynamodb',
        source: 'lambda',
        target: 'dynamodb',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Sync', iamPermissions: [] },
      },
    ],
  },
  {
    id: 'fan-out-notifications',
    name: 'Fan-Out Notification System',
    description: 'SNS fans out a single event to multiple SQS queues for parallel processing by independent Lambda consumers.',
    nodes: [
      {
        id: 'sns',
        type: 'awsNode',
        position: { x: 100, y: 300 },
        data: { service: 'sns', label: 'SNS Topic' },
      },
      {
        id: 'sqs1',
        type: 'awsNode',
        position: { x: 380, y: 160 },
        data: { service: 'sqs', label: 'SQS Queue A', visibilityTimeout: 180, isFifo: false },
      },
      {
        id: 'sqs2',
        type: 'awsNode',
        position: { x: 380, y: 440 },
        data: { service: 'sqs', label: 'SQS Queue B', visibilityTimeout: 180, isFifo: false },
      },
      {
        id: 'lambda1',
        type: 'awsNode',
        position: { x: 660, y: 160 },
        data: { service: 'lambda', label: 'Lambda Consumer A', timeout: 30, memorySize: 128, hasDeadLetterQueue: true },
      },
      {
        id: 'lambda2',
        type: 'awsNode',
        position: { x: 660, y: 440 },
        data: { service: 'lambda', label: 'Lambda Consumer B', timeout: 30, memorySize: 128, hasDeadLetterQueue: true },
      },
    ],
    edges: [
      {
        id: 'e-sns-sqs1',
        source: 'sns',
        target: 'sqs1',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Async', iamPermissions: [] },
      },
      {
        id: 'e-sns-sqs2',
        source: 'sns',
        target: 'sqs2',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Async', iamPermissions: [] },
      },
      {
        id: 'e-sqs1-lambda1',
        source: 'sqs1',
        target: 'lambda1',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Async', iamPermissions: [] },
      },
      {
        id: 'e-sqs2-lambda2',
        source: 'sqs2',
        target: 'lambda2',
        type: 'awsEdge',
        animated: true,
        data: { authType: 'NONE', invocationType: 'Async', iamPermissions: [] },
      },
    ],
  },
];
